---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/data_bags
  environments_path: test/environments
  client_rb:
    environment: test

platforms:
  - name: ubuntu-14.04

suites:
  - name: gateway
    run_list:
      - recipe[strongswanaws::server]
      - recipe[strongswanaws::tunnels]

